import Head from "next/head";
import React from "react";
import { Inter } from "@next/font/google";
import { SmartInput } from "@foundationui/smart-input";

export default function Home() {
  const [value, setValue] = React.useState("");
  return (
    <>
      <Head>
        <title>Shakespearean SmartInput</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "6rem",
          minHeight: "100vh",
        }}
      >
        <div style={{ width: "100%" }}>
          <h1 className="text-2xl font-bold text-gray-700 pb-2">
            Shakespearean <code className="text-md">{"<SmartInput>"}</code>
          </h1>
          <SmartInput
            model="foundation/shakespeare"
            className="border border-slate-500 rounded-md p-1 hover:border-sky-500 focus:border-sky-500"
            placeholder="Start composing a sonnet..."
            renderText={(props: any) => (
              <span className="text-gray-600/100" {...props} />
            )}
            renderCompletion={(props: any) => (
              <span className="text-gray-600/40" {...props} />
            )}
            renderPlaceholder={(props: any) => (
              <span className="text-gray-600/40" {...props} />
            )}
            value={value}
            onChange={setValue}
            multiline={true}
          />
        </div>
      </main>
    </>
  );
}
